CFLAG = -Wall -pedantic -Wno-comment -O3 -std=c89
LDFLAGS = -l

ifeq ($(OS),Windows_NT)
	LDFLAGS += pdcurses
else
	LDFLAGS += ncurses
endif
 
all: minesweeper

board.o: board.h board.c
	gcc $(CFLAG) -c board.c

game.o: game.h game.c
	gcc $(CFLAG) -c game.c

display.o: display.h display.c
	gcc $(CFLAG) -c display.c

minesweeper: board.h game.h display.h board.o game.o display.o main.c
	gcc $(CFLAG) board.o game.o display.o main.c -o minesweeper $(LDFLAGS)

clean:
	rm -rf *.o minesweeper 
